### ISSUE TITLE
Breaks Visual Editor

### ISSUE THREAD

**Issue by kmuncie** [Rahe/Simple-responsive-images#1]
Running Wordpress 3.3.1 and anytime I have the plugin activated it breaks the visual editor.

**Comment by Rahe** [comment]
Hi,

Can you report me the php/javascript error ?

Rahe

**Comment by celsomiranda** [comment]
I have this problem as well. My irst thought was the php_memory limits, but it's not.

I can't look for the error now, I'll post as soon as I find out more.

**Comment by Rahe** [comment]
Cool, thank you !
I fail to reproduce the issue :/

**Comment by celsomiranda** [comment]
In the Google Chrome console I get this:

Uncaught TypeError: Cannot call method 'parse' of undefined
m.create.setContent        wp-tinymce.php:2
m.create.load                  wp-tinymce.php:2
m.create.show                wp-tinymce.php:2
switchEditors.go             load-scripts.php:502
switchEditors.switchto    load-scripts.php:502
(anonymous function)post.php:436
onclick

**Comment by Rahe** [comment]
Hi,

Are you on a custom post_type ? Is there any plugin adding a button to the tinymce ? or have you a plugin wich modifying tinymce ?

**Comment by celsomiranda** [comment]
This happens in posts and pages, haven't tried in custom post_type.

The other plugins I have installed are:
- Akismet
- Contact Form 7
- Fancybox for Wordpress
- Secure Wordpress
- wp-typography

All updated to the latest version

**Comment by Rahe** [comment]
Hi,
Thank you for the plugins, I will look at this issue as soon as possible :)

**Comment by mswartz** [comment]
Hi Rahe, same thing happened to me. My client writes posts in the visual editor, and she wrote out a post and saved it, but it blew away the text. Something is conflicting with the visual editor function. Disabled it and it started to work again just fine. Just a very standard post type, no crazy plugins installed. Running WP 3.3.2.

**Comment by ohryan** [comment]
Found a solution. 

I do not understand the tiny_mce_before_init WP filter so I cannot explain what's happening. The error is occurring in the loops in /includes/class.admin.php on lines 48 - 54: 

``` php
foreach ( $elements as $element => $attributes ) {
    if ( count( $attributes ) > 0 ) {
        $attributes = array_filter( $attributes );
        $eleList[] = $element . '[' . implode( '|', $attributes ) . ']';
    } else {
        $eleList[] = $element;
    }
}
```

In some cases, some elements of $attributes are null. 

Running the array through array_filter() fixes the bug: 

``` php
foreach ( $elements as $element => $attributes ) {
    if ( count( $attributes ) > 0 ) {
        $attributes = array_filter( $attributes );
        $eleList[] = $element . '[' . implode( '|', $attributes ) . ']';
    } else {
        $eleList[] = $element;
    }
}
```

That said, I'm not actually confident that this plugin functions in 3.3.2.
